wip

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -5,9 +5,9 @@ name: Python package
 
 on:
   push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+    branches: [ master, dev/github_actions ]
+  #pull_request:
+  #  branches: [ master ]
 
 jobs:
   build:
@@ -57,17 +57,17 @@ jobs:
       run: |
         python run_tests.py
     - name: Sign and Publish
-      if: ${{ !env.ACT }}
       run: |
         GPG_EXECUTABLE=gpg
         $GPG_EXECUTABLE --version
         openssl version
         $GPG_EXECUTABLE --list-keys
         export PYUTILS_CI_GITHUB_SECRET=${{ secrets.PYUTILS_CI_GITHUB_SECRET }}
-        TSP=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -md MD5 -pass env:TSP -d -a -in dev/travis_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
-        TSP=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -md MD5 -pass env:TSP -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
-        TSP=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -md MD5 -pass env:TSP -d -a -in dev/travis_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
-        $GPG_EXECUTABLE --list-keys
+        GLKWS=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/cci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
+        GLKWS=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/cci_gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
+        GLKWS=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/cci_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
+        $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
+        $GPG_EXECUTABLE --list-keys  
         MB_PYTHON_TAG=$(python -c "import setup; print(setup.MB_PYTHON_TAG)")
         VERSION=$(python -c "import setup; print(setup.VERSION)") 
         pip install twine
@@ -76,7 +76,7 @@ jobs:
         GPG_KEYID=$(cat dev/public_gpg_key)
         echo "GPG_KEYID = '$GPG_KEYID'"
         #
-        export TWINE_REPOSITORY_URL=https://pypi.python.org/pypi
+        export TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/
         export PYUTILS_TEST_TWINE_USERNAME=${{ secrets.PYUTILS_TEST_TWINE_USERNAME }}
         export PYUTILS_TEST_TWINE_PASSWORD=${{ secrets.PYUTILS_TEST_TWINE_PASSWORD }}
         MB_PYTHON_TAG=$MB_PYTHON_TAG \
@@ -89,7 +89,7 @@ jobs:
         #
         #export PYUTILS_TWINE_USERNAME=${{ secrets.PYUTILS_TWINE_USERNAME }}
         #export PYUTILS_TWINE_PASSWORD=${{ secrets.PYUTILS_TWINE_PASSWORD }}
-        #export TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/
+        #export TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
         #MB_PYTHON_TAG=$MB_PYTHON_TAG \
         #    DO_GPG=True GPG_KEYID=$GPG_KEYID \
         #    TWINE_PASSWORD=$PYUTILS_TWINE_PASSWORD \
@@ -121,20 +121,21 @@ jobs:
        
 ###
 
-#__doc__: |
-#    # How to run locally
-#    # https://packaging.python.org/guides/using-testpypi/
-#    cd $HOME/code
-#    git clone https://github.com/nektos/act.git $HOME/code/act
-#    cd $HOME/code/act
-#    chmod +x install.sh
-#    ./install.sh -b $HOME/.local/opt/act
-#    cd $HOME/code/line_profiler
+__doc__: |
+    # How to run locally
+    # https://packaging.python.org/guides/using-testpypi/
+    cd $HOME/code
+    git clone https://github.com/nektos/act.git $HOME/code/act
+    cd $HOME/code/act
+    chmod +x install.sh
+    ./install.sh -b $HOME/.local/opt/act
+    cd $HOME/code/line_profiler
 
-#    load_secrets
-#    $HOME/.local/opt/act/act \
-#        --secret=PYUTILS_TWINE_PASSWORD=$PYUTILS_TWINE_PASSWORD \
-#        --secret=PYUTILS_TWINE_USERNAME=$PYUTILS_TWINE_USERNAME \
-#        --secret=PYUTILS_CI_GITHUB_SECRET=$PYUTILS_CI_GITHUB_SECRET \
-#        --secret=PYUTILS_TEST_TWINE_USERNAME=$PYUTILS_TEST_TWINE_USERNAME \
-#        --secret=PYUTILS_TEST_TWINE_PASSWORD=$PYUTILS_TEST_TWINE_PASSWORD 
+    load_secrets
+    unset GITHUB_TOKEN
+    $HOME/.local/opt/act/act \
+        --secret=PYUTILS_TWINE_PASSWORD=$PYUTILS_TWINE_PASSWORD \
+        --secret=PYUTILS_TWINE_USERNAME=$PYUTILS_TWINE_USERNAME \
+        --secret=PYUTILS_CI_GITHUB_SECRET=$PYUTILS_CI_GITHUB_SECRET \
+        --secret=PYUTILS_TEST_TWINE_USERNAME=$PYUTILS_TEST_TWINE_USERNAME \
+        --secret=PYUTILS_TEST_TWINE_PASSWORD=$PYUTILS_TEST_TWINE_PASSWORD 
